<a href="https://colab.research.google.com/github/anajikadam/Polars-alternative_Pandas/blob/main/Polars_alternative_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Super Fast Dataframe Library for Python: Polars

https://github.com/pola-rs/polars

In [8]:
# !pip install polar
!pip install polars

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting polars
  Downloading polars-0.16.9-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.4/15.4 MB 53.0 MB/s eta 0:00:00
Requirement already satisfied: typing_extensions>=4.0.1 in /usr/local/lib/python3.8/dist-packages (from polars) (4.5.0)
Installing collected packages: polars
Successfully installed polars-0.16.9

Here are some reasons why you should choose polars.

- It uses all available cores on your computer.
- It optimizes queries to reduce unneeded work/memory allocations.
- It handles datasets larger than your available RAM.
- It has a strict schema (data types should be known before running the query).

In [1]:
import pandas as pd
import polars as pl

In [3]:
df = pl.read_csv("StudentsPerformance.csv")

[Docs](https://pola-rs.github.io/polars-book/user-guide/introduction.html)

In [4]:
type(df)

polars.internals.dataframe.frame.DataFrame

In [5]:
pandas_df = df.to_pandas()
type(pandas_df)

pandas.core.frame.DataFrame

In [12]:
df.head()

shape: (5, 9)
┌─────┬────────┬────────────┬────────────┬─────┬────────────┬────────────┬────────────┬────────────┐
│ id  ┆ gender ┆ race/ethni ┆ parental   ┆ ... ┆ test prepa ┆ math score ┆ reading    ┆ writing    │
│ --- ┆ ---    ┆ city       ┆ level of   ┆     ┆ ration     ┆ ---        ┆ score      ┆ score      │
│ i64 ┆ str    ┆ ---        ┆ education  ┆     ┆ course     ┆ i64        ┆ ---        ┆ ---        │
│     ┆        ┆ str        ┆ ---        ┆     ┆ ---        ┆            ┆ i64        ┆ i64        │
│     ┆        ┆            ┆ str        ┆     ┆ str        ┆            ┆            ┆            │
╞═════╪════════╪════════════╪════════════╪═════╪════════════╪════════════╪════════════╪════════════╡
│ 1   ┆ female ┆ group B    ┆ bachelor's ┆ ... ┆ none       ┆ 72         ┆ 72         ┆ 74         │
│     ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆            ┆            │
│ 2   ┆ female ┆ group C    ┆ some       ┆ ... ┆ completed  ┆ 69         ┆ 90         ┆ 88         │
│     ┆        ┆            ┆ college    ┆     ┆            ┆            ┆            ┆            │
│ 3   ┆ female ┆ group B    ┆ master's   ┆ ... ┆ none       ┆ 90         ┆ 95         ┆ 93         │
│     ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆            ┆            │
│ 4   ┆ male   ┆ group A    ┆ associate' ┆ ... ┆ none       ┆ 47         ┆ 57         ┆ 44         │
│     ┆        ┆            ┆ s degree   ┆     ┆            ┆            ┆            ┆            │
│ 5   ┆ male   ┆ group C    ┆ some       ┆ ... ┆ none       ┆ 76         ┆ 78         ┆ 75         │
│     ┆        ┆            ┆ college    ┆     ┆            ┆            ┆            ┆            │
└─────┴────────┴────────────┴────────────┴─────┴────────────┴────────────┴────────────┴────────────┘

In [13]:
# list of columns
df.columns

['id',
 'gender',
 'race/ethnicity',
 'parental level of education',
 'lunch',
 'test preparation course',
 'math score',
 'reading score',
 'writing score']

In [14]:
# Select 1 column
df.select(pl.col('gender'))

shape: (1000, 1)
┌────────┐
│ gender │
│ ---    │
│ str    │
╞════════╡
│ female │
│ female │
│ female │
│ male   │
│ ...    │
│ male   │
│ female │
│ female │
│ female │
└────────┘

In [15]:
# Select 2+ columns
df.select(pl.col(['gender', 'math score']))

shape: (1000, 2)
┌────────┬────────────┐
│ gender ┆ math score │
│ ---    ┆ ---        │
│ str    ┆ i64        │
╞════════╪════════════╡
│ female ┆ 72         │
│ female ┆ 69         │
│ female ┆ 90         │
│ male   ┆ 47         │
│ ...    ┆ ...        │
│ male   ┆ 62         │
│ female ┆ 59         │
│ female ┆ 68         │
│ female ┆ 77         │
└────────┴────────────┘

In [16]:
# Select all columns
df.select(pl.col('*'))

shape: (1000, 9)
┌──────┬────────┬────────────┬────────────┬─────┬────────────┬──────────┬────────────┬────────────┐
│ id   ┆ gender ┆ race/ethni ┆ parental   ┆ ... ┆ test prepa ┆ math     ┆ reading    ┆ writing    │
│ ---  ┆ ---    ┆ city       ┆ level of   ┆     ┆ ration     ┆ score    ┆ score      ┆ score      │
│ i64  ┆ str    ┆ ---        ┆ education  ┆     ┆ course     ┆ ---      ┆ ---        ┆ ---        │
│      ┆        ┆ str        ┆ ---        ┆     ┆ ---        ┆ i64      ┆ i64        ┆ i64        │
│      ┆        ┆            ┆ str        ┆     ┆ str        ┆          ┆            ┆            │
╞══════╪════════╪════════════╪════════════╪═════╪════════════╪══════════╪════════════╪════════════╡
│ 1    ┆ female ┆ group B    ┆ bachelor's ┆ ... ┆ none       ┆ 72       ┆ 72         ┆ 74         │
│      ┆        ┆            ┆ degree     ┆     ┆            ┆          ┆            ┆            │
│ 2    ┆ female ┆ group C    ┆ some       ┆ ... ┆ completed  ┆ 69       ┆ 90         ┆ 88         │
│      ┆        ┆            ┆ college    ┆     ┆            ┆          ┆            ┆            │
│ 3    ┆ female ┆ group B    ┆ master's   ┆ ... ┆ none       ┆ 90       ┆ 95         ┆ 93         │
│      ┆        ┆            ┆ degree     ┆     ┆            ┆          ┆            ┆            │
│ 4    ┆ male   ┆ group A    ┆ associate' ┆ ... ┆ none       ┆ 47       ┆ 57         ┆ 44         │
│      ┆        ┆            ┆ s degree   ┆     ┆            ┆          ┆            ┆            │
│ ...  ┆ ...    ┆ ...        ┆ ...        ┆ ... ┆ ...        ┆ ...      ┆ ...        ┆ ...        │
│ 997  ┆ male   ┆ group C    ┆ high       ┆ ... ┆ none       ┆ 62       ┆ 55         ┆ 55         │
│      ┆        ┆            ┆ school     ┆     ┆            ┆          ┆            ┆            │
│ 998  ┆ female ┆ group C    ┆ high       ┆ ... ┆ completed  ┆ 59       ┆ 71         ┆ 65         │
│      ┆        ┆            ┆ school     ┆     ┆            ┆          ┆            ┆            │
│ 999  ┆ female ┆ group D    ┆ some       ┆ ... ┆ completed  ┆ 68       ┆ 78         ┆ 77         │
│      ┆        ┆            ┆ college    ┆     ┆            ┆          ┆            ┆            │
│ 1000 ┆ female ┆ group D    ┆ some       ┆ ... ┆ none       ┆ 77       ┆ 86         ┆ 86         │
│      ┆        ┆            ┆ college    ┆     ┆            ┆          ┆            ┆            │
└──────┴────────┴────────────┴────────────┴─────┴────────────┴──────────┴────────────┴────────────┘

In [17]:
# polars: create "sum" column
df.with_columns(
    (pl.col('math score') + pl.col('reading score')).alias("sum")
)

# pandas: df['sum'] = df['math score'] + df['reading score']

shape: (1000, 10)
┌──────┬────────┬────────────┬─────────────────┬─────┬────────────┬─────────┬────────────────┬─────┐
│ id   ┆ gender ┆ race/ethni ┆ parental level  ┆ ... ┆ math score ┆ reading ┆ writing score  ┆ sum │
│ ---  ┆ ---    ┆ city       ┆ of education    ┆     ┆ ---        ┆ score   ┆ ---            ┆ --- │
│ i64  ┆ str    ┆ ---        ┆ ---             ┆     ┆ i64        ┆ ---     ┆ i64            ┆ i64 │
│      ┆        ┆ str        ┆ str             ┆     ┆            ┆ i64     ┆                ┆     │
╞══════╪════════╪════════════╪═════════════════╪═════╪════════════╪═════════╪════════════════╪═════╡
│ 1    ┆ female ┆ group B    ┆ bachelor's      ┆ ... ┆ 72         ┆ 72      ┆ 74             ┆ 144 │
│      ┆        ┆            ┆ degree          ┆     ┆            ┆         ┆                ┆     │
│ 2    ┆ female ┆ group C    ┆ some college    ┆ ... ┆ 69         ┆ 90      ┆ 88             ┆ 159 │
│ 3    ┆ female ┆ group B    ┆ master's degree ┆ ... ┆ 90         ┆ 95      ┆ 93             ┆ 185 │
│ 4    ┆ male   ┆ group A    ┆ associate's     ┆ ... ┆ 47         ┆ 57      ┆ 44             ┆ 104 │
│      ┆        ┆            ┆ degree          ┆     ┆            ┆         ┆                ┆     │
│ ...  ┆ ...    ┆ ...        ┆ ...             ┆ ... ┆ ...        ┆ ...     ┆ ...            ┆ ... │
│ 997  ┆ male   ┆ group C    ┆ high school     ┆ ... ┆ 62         ┆ 55      ┆ 55             ┆ 117 │
│ 998  ┆ female ┆ group C    ┆ high school     ┆ ... ┆ 59         ┆ 71      ┆ 65             ┆ 130 │
│ 999  ┆ female ┆ group D    ┆ some college    ┆ ... ┆ 68         ┆ 78      ┆ 77             ┆ 146 │
│ 1000 ┆ female ┆ group D    ┆ some college    ┆ ... ┆ 77         ┆ 86      ┆ 86             ┆ 163 │
└──────┴────────┴────────────┴─────────────────┴─────┴────────────┴─────────┴────────────────┴─────┘

In [18]:
# polars: create "average" column
df.with_columns(
    pl.col(['math score', 'reading score', 'writing score']).mean().alias('average')
)

# pandas: df['average'] = df[['math score', 'reading score', 'writing score']].mean(axis=1)

shape: (1000, 10)
┌──────┬────────┬────────────┬────────────┬─────┬────────────┬────────────┬─────────┬─────────┐
│ id   ┆ gender ┆ race/ethni ┆ parental   ┆ ... ┆ math score ┆ reading    ┆ writing ┆ average │
│ ---  ┆ ---    ┆ city       ┆ level of   ┆     ┆ ---        ┆ score      ┆ score   ┆ ---     │
│ i64  ┆ str    ┆ ---        ┆ education  ┆     ┆ i64        ┆ ---        ┆ ---     ┆ f64     │
│      ┆        ┆ str        ┆ ---        ┆     ┆            ┆ i64        ┆ i64     ┆         │
│      ┆        ┆            ┆ str        ┆     ┆            ┆            ┆         ┆         │
╞══════╪════════╪════════════╪════════════╪═════╪════════════╪════════════╪═════════╪═════════╡
│ 1    ┆ female ┆ group B    ┆ bachelor's ┆ ... ┆ 72         ┆ 72         ┆ 74      ┆ 68.054  │
│      ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆         ┆         │
│ 2    ┆ female ┆ group C    ┆ some       ┆ ... ┆ 69         ┆ 90         ┆ 88      ┆ 68.054  │
│      ┆        ┆            ┆ college    ┆     ┆            ┆            ┆         ┆         │
│ 3    ┆ female ┆ group B    ┆ master's   ┆ ... ┆ 90         ┆ 95         ┆ 93      ┆ 68.054  │
│      ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆         ┆         │
│ 4    ┆ male   ┆ group A    ┆ associate' ┆ ... ┆ 47         ┆ 57         ┆ 44      ┆ 68.054  │
│      ┆        ┆            ┆ s degree   ┆     ┆            ┆            ┆         ┆         │
│ ...  ┆ ...    ┆ ...        ┆ ...        ┆ ... ┆ ...        ┆ ...        ┆ ...     ┆ ...     │
│ 997  ┆ male   ┆ group C    ┆ high       ┆ ... ┆ 62         ┆ 55         ┆ 55      ┆ 68.054  │
│      ┆        ┆            ┆ school     ┆     ┆            ┆            ┆         ┆         │
│ 998  ┆ female ┆ group C    ┆ high       ┆ ... ┆ 59         ┆ 71         ┆ 65      ┆ 68.054  │
│      ┆        ┆            ┆ school     ┆     ┆            ┆            ┆         ┆         │
│ 999  ┆ female ┆ group D    ┆ some       ┆ ... ┆ 68         ┆ 78         ┆ 77      ┆ 68.054  │
│      ┆        ┆            ┆ college    ┆     ┆            ┆            ┆         ┆         │
│ 1000 ┆ female ┆ group D    ┆ some       ┆ ... ┆ 77         ┆ 86         ┆ 86      ┆ 68.054  │
│      ┆        ┆            ┆ college    ┆     ┆            ┆            ┆         ┆         │
└──────┴────────┴────────────┴────────────┴─────┴────────────┴────────────┴─────────┴─────────┘

In [19]:
# polars: simple filtering
df.filter(pl.col('gender')=='female')

# pandas: df[df['gender'] == 'female']

shape: (518, 9)
┌──────┬────────┬────────────┬────────────┬─────┬────────────┬──────────┬────────────┬────────────┐
│ id   ┆ gender ┆ race/ethni ┆ parental   ┆ ... ┆ test prepa ┆ math     ┆ reading    ┆ writing    │
│ ---  ┆ ---    ┆ city       ┆ level of   ┆     ┆ ration     ┆ score    ┆ score      ┆ score      │
│ i64  ┆ str    ┆ ---        ┆ education  ┆     ┆ course     ┆ ---      ┆ ---        ┆ ---        │
│      ┆        ┆ str        ┆ ---        ┆     ┆ ---        ┆ i64      ┆ i64        ┆ i64        │
│      ┆        ┆            ┆ str        ┆     ┆ str        ┆          ┆            ┆            │
╞══════╪════════╪════════════╪════════════╪═════╪════════════╪══════════╪════════════╪════════════╡
│ 1    ┆ female ┆ group B    ┆ bachelor's ┆ ... ┆ none       ┆ 72       ┆ 72         ┆ 74         │
│      ┆        ┆            ┆ degree     ┆     ┆            ┆          ┆            ┆            │
│ 2    ┆ female ┆ group C    ┆ some       ┆ ... ┆ completed  ┆ 69       ┆ 90         ┆ 88         │
│      ┆        ┆            ┆ college    ┆     ┆            ┆          ┆            ┆            │
│ 3    ┆ female ┆ group B    ┆ master's   ┆ ... ┆ none       ┆ 90       ┆ 95         ┆ 93         │
│      ┆        ┆            ┆ degree     ┆     ┆            ┆          ┆            ┆            │
│ 6    ┆ female ┆ group B    ┆ associate' ┆ ... ┆ none       ┆ 71       ┆ 83         ┆ 78         │
│      ┆        ┆            ┆ s degree   ┆     ┆            ┆          ┆            ┆            │
│ ...  ┆ ...    ┆ ...        ┆ ...        ┆ ... ┆ ...        ┆ ...      ┆ ...        ┆ ...        │
│ 996  ┆ female ┆ group E    ┆ master's   ┆ ... ┆ completed  ┆ 88       ┆ 99         ┆ 95         │
│      ┆        ┆            ┆ degree     ┆     ┆            ┆          ┆            ┆            │
│ 998  ┆ female ┆ group C    ┆ high       ┆ ... ┆ completed  ┆ 59       ┆ 71         ┆ 65         │
│      ┆        ┆            ┆ school     ┆     ┆            ┆          ┆            ┆            │
│ 999  ┆ female ┆ group D    ┆ some       ┆ ... ┆ completed  ┆ 68       ┆ 78         ┆ 77         │
│      ┆        ┆            ┆ college    ┆     ┆            ┆          ┆            ┆            │
│ 1000 ┆ female ┆ group D    ┆ some       ┆ ... ┆ none       ┆ 77       ┆ 86         ┆ 86         │
│      ┆        ┆            ┆ college    ┆     ┆            ┆          ┆            ┆            │
└──────┴────────┴────────────┴────────────┴─────┴────────────┴──────────┴────────────┴────────────┘

In [20]:
# Multiple filtering 
df.filter(
    (pl.col('gender')=='female') &
    (pl.col('race/ethnicity')=='group B')
)

# pandas: df[(df['gender'] == 'female') & (df['race/ethnicity'] == 'group B')]

shape: (104, 9)
┌─────┬────────┬────────────┬────────────┬─────┬────────────┬────────────┬────────────┬────────────┐
│ id  ┆ gender ┆ race/ethni ┆ parental   ┆ ... ┆ test prepa ┆ math score ┆ reading    ┆ writing    │
│ --- ┆ ---    ┆ city       ┆ level of   ┆     ┆ ration     ┆ ---        ┆ score      ┆ score      │
│ i64 ┆ str    ┆ ---        ┆ education  ┆     ┆ course     ┆ i64        ┆ ---        ┆ ---        │
│     ┆        ┆ str        ┆ ---        ┆     ┆ ---        ┆            ┆ i64        ┆ i64        │
│     ┆        ┆            ┆ str        ┆     ┆ str        ┆            ┆            ┆            │
╞═════╪════════╪════════════╪════════════╪═════╪════════════╪════════════╪════════════╪════════════╡
│ 1   ┆ female ┆ group B    ┆ bachelor's ┆ ... ┆ none       ┆ 72         ┆ 72         ┆ 74         │
│     ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆            ┆            │
│ 3   ┆ female ┆ group B    ┆ master's   ┆ ... ┆ none       ┆ 90         ┆ 95         ┆ 93         │
│     ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆            ┆            │
│ 6   ┆ female ┆ group B    ┆ associate' ┆ ... ┆ none       ┆ 71         ┆ 83         ┆ 78         │
│     ┆        ┆            ┆ s degree   ┆     ┆            ┆            ┆            ┆            │
│ 7   ┆ female ┆ group B    ┆ some       ┆ ... ┆ completed  ┆ 88         ┆ 95         ┆ 92         │
│     ┆        ┆            ┆ college    ┆     ┆            ┆            ┆            ┆            │
│ ... ┆ ...    ┆ ...        ┆ ...        ┆ ... ┆ ...        ┆ ...        ┆ ...        ┆ ...        │
│ 945 ┆ female ┆ group B    ┆ high       ┆ ... ┆ none       ┆ 58         ┆ 68         ┆ 61         │
│     ┆        ┆            ┆ school     ┆     ┆            ┆            ┆            ┆            │
│ 970 ┆ female ┆ group B    ┆ bachelor's ┆ ... ┆ none       ┆ 75         ┆ 84         ┆ 80         │
│     ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆            ┆            │
│ 981 ┆ female ┆ group B    ┆ high       ┆ ... ┆ none       ┆ 8          ┆ 24         ┆ 23         │
│     ┆        ┆            ┆ school     ┆     ┆            ┆            ┆            ┆            │
│ 992 ┆ female ┆ group B    ┆ some high  ┆ ... ┆ completed  ┆ 65         ┆ 82         ┆ 78         │
│     ┆        ┆            ┆ school     ┆     ┆            ┆            ┆            ┆            │
└─────┴────────┴────────────┴────────────┴─────┴────────────┴────────────┴────────────┴────────────┘

In [21]:
# Group by
df.groupby("race/ethnicity").count()

shape: (5, 2)
┌────────────────┬───────┐
│ race/ethnicity ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ group A        ┆ 89    │
│ group B        ┆ 190   │
│ group C        ┆ 319   │
│ group D        ┆ 262   │
│ group E        ┆ 140   │
└────────────────┴───────┘

In [22]:
df2 = pl.read_csv("LanguageScore.csv")

In [23]:
df.head()

shape: (5, 9)
┌─────┬────────┬────────────┬────────────┬─────┬────────────┬────────────┬────────────┬────────────┐
│ id  ┆ gender ┆ race/ethni ┆ parental   ┆ ... ┆ test prepa ┆ math score ┆ reading    ┆ writing    │
│ --- ┆ ---    ┆ city       ┆ level of   ┆     ┆ ration     ┆ ---        ┆ score      ┆ score      │
│ i64 ┆ str    ┆ ---        ┆ education  ┆     ┆ course     ┆ i64        ┆ ---        ┆ ---        │
│     ┆        ┆ str        ┆ ---        ┆     ┆ ---        ┆            ┆ i64        ┆ i64        │
│     ┆        ┆            ┆ str        ┆     ┆ str        ┆            ┆            ┆            │
╞═════╪════════╪════════════╪════════════╪═════╪════════════╪════════════╪════════════╪════════════╡
│ 1   ┆ female ┆ group B    ┆ bachelor's ┆ ... ┆ none       ┆ 72         ┆ 72         ┆ 74         │
│     ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆            ┆            │
│ 2   ┆ female ┆ group C    ┆ some       ┆ ... ┆ completed  ┆ 69         ┆ 90         ┆ 88         │
│     ┆        ┆            ┆ college    ┆     ┆            ┆            ┆            ┆            │
│ 3   ┆ female ┆ group B    ┆ master's   ┆ ... ┆ none       ┆ 90         ┆ 95         ┆ 93         │
│     ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆            ┆            │
│ 4   ┆ male   ┆ group A    ┆ associate' ┆ ... ┆ none       ┆ 47         ┆ 57         ┆ 44         │
│     ┆        ┆            ┆ s degree   ┆     ┆            ┆            ┆            ┆            │
│ 5   ┆ male   ┆ group C    ┆ some       ┆ ... ┆ none       ┆ 76         ┆ 78         ┆ 75         │
│     ┆        ┆            ┆ college    ┆     ┆            ┆            ┆            ┆            │
└─────┴────────┴────────────┴────────────┴─────┴────────────┴────────────┴────────────┴────────────┘

In [24]:
df2.head()

shape: (5, 2)
┌─────┬────────────────┐
│ id  ┆ language score │
│ --- ┆ ---            │
│ i64 ┆ i64            │
╞═════╪════════════════╡
│ 1   ┆ 74             │
│ 2   ┆ 67             │
│ 3   ┆ 34             │
│ 4   ┆ 33             │
│ 5   ┆ 75             │
└─────┴────────────────┘

In [25]:
# Join dataframes
df.join(df2, on='id')

shape: (100, 10)
┌─────┬────────┬────────────┬────────────┬─────┬────────────┬────────────┬────────────┬────────────┐
│ id  ┆ gender ┆ race/ethni ┆ parental   ┆ ... ┆ math score ┆ reading    ┆ writing    ┆ language   │
│ --- ┆ ---    ┆ city       ┆ level of   ┆     ┆ ---        ┆ score      ┆ score      ┆ score      │
│ i64 ┆ str    ┆ ---        ┆ education  ┆     ┆ i64        ┆ ---        ┆ ---        ┆ ---        │
│     ┆        ┆ str        ┆ ---        ┆     ┆            ┆ i64        ┆ i64        ┆ i64        │
│     ┆        ┆            ┆ str        ┆     ┆            ┆            ┆            ┆            │
╞═════╪════════╪════════════╪════════════╪═════╪════════════╪════════════╪════════════╪════════════╡
│ 1   ┆ female ┆ group B    ┆ bachelor's ┆ ... ┆ 72         ┆ 72         ┆ 74         ┆ 74         │
│     ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆            ┆            │
│ 2   ┆ female ┆ group C    ┆ some       ┆ ... ┆ 69         ┆ 90         ┆ 88         ┆ 67         │
│     ┆        ┆            ┆ college    ┆     ┆            ┆            ┆            ┆            │
│ 3   ┆ female ┆ group B    ┆ master's   ┆ ... ┆ 90         ┆ 95         ┆ 93         ┆ 34         │
│     ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆            ┆            │
│ 4   ┆ male   ┆ group A    ┆ associate' ┆ ... ┆ 47         ┆ 57         ┆ 44         ┆ 33         │
│     ┆        ┆            ┆ s degree   ┆     ┆            ┆            ┆            ┆            │
│ ... ┆ ...    ┆ ...        ┆ ...        ┆ ... ┆ ...        ┆ ...        ┆ ...        ┆ ...        │
│ 97  ┆ male   ┆ group B    ┆ some high  ┆ ... ┆ 65         ┆ 66         ┆ 62         ┆ 87         │
│     ┆        ┆            ┆ school     ┆     ┆            ┆            ┆            ┆            │
│ 98  ┆ female ┆ group E    ┆ some       ┆ ... ┆ 63         ┆ 72         ┆ 70         ┆ 66         │
│     ┆        ┆            ┆ college    ┆     ┆            ┆            ┆            ┆            │
│ 99  ┆ female ┆ group D    ┆ some       ┆ ... ┆ 58         ┆ 67         ┆ 62         ┆ 94         │
│     ┆        ┆            ┆ college    ┆     ┆            ┆            ┆            ┆            │
│ 100 ┆ female ┆ group D    ┆ bachelor's ┆ ... ┆ 65         ┆ 67         ┆ 62         ┆ 75         │
│     ┆        ┆            ┆ degree     ┆     ┆            ┆            ┆            ┆            │
└─────┴────────┴────────────┴────────────┴─────┴────────────┴────────────┴────────────┴────────────┘

In [ ]:
# Inner, left and outer join
df.join(df2, on='id', how='inner')
df.join(df2, on='id', how='left')
df.join(df2, on='id', how='outer')

In [26]:
# Concatenate dataframes
pl.concat([df, df2], how="horizontal")

DuplicateError: ignored

In [27]:
# drop column "id" in df2
df2 = df2.drop("id")

# Concatenate dataframes
pl.concat([df, df2], how="horizontal")

shape: (1000, 10)
┌──────┬────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ id   ┆ gender ┆ race/ethni ┆ parental   ┆ ... ┆ math     ┆ reading    ┆ writing    ┆ language   │
│ ---  ┆ ---    ┆ city       ┆ level of   ┆     ┆ score    ┆ score      ┆ score      ┆ score      │
│ i64  ┆ str    ┆ ---        ┆ education  ┆     ┆ ---      ┆ ---        ┆ ---        ┆ ---        │
│      ┆        ┆ str        ┆ ---        ┆     ┆ i64      ┆ i64        ┆ i64        ┆ i64        │
│      ┆        ┆            ┆ str        ┆     ┆          ┆            ┆            ┆            │
╞══════╪════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 1    ┆ female ┆ group B    ┆ bachelor's ┆ ... ┆ 72       ┆ 72         ┆ 74         ┆ 74         │
│      ┆        ┆            ┆ degree     ┆     ┆          ┆            ┆            ┆            │
│ 2    ┆ female ┆ group C    ┆ some       ┆ ... ┆ 69       ┆ 90         ┆ 88         ┆ 67         │
│      ┆        ┆            ┆ college    ┆     ┆          ┆            ┆            ┆            │
│ 3    ┆ female ┆ group B    ┆ master's   ┆ ... ┆ 90       ┆ 95         ┆ 93         ┆ 34         │
│      ┆        ┆            ┆ degree     ┆     ┆          ┆            ┆            ┆            │
│ 4    ┆ male   ┆ group A    ┆ associate' ┆ ... ┆ 47       ┆ 57         ┆ 44         ┆ 33         │
│      ┆        ┆            ┆ s degree   ┆     ┆          ┆            ┆            ┆            │
│ ...  ┆ ...    ┆ ...        ┆ ...        ┆ ... ┆ ...      ┆ ...        ┆ ...        ┆ ...        │
│ 997  ┆ male   ┆ group C    ┆ high       ┆ ... ┆ 62       ┆ 55         ┆ 55         ┆ null       │
│      ┆        ┆            ┆ school     ┆     ┆          ┆            ┆            ┆            │
│ 998  ┆ female ┆ group C    ┆ high       ┆ ... ┆ 59       ┆ 71         ┆ 65         ┆ null       │
│      ┆        ┆            ┆ school     ┆     ┆          ┆            ┆            ┆            │
│ 999  ┆ female ┆ group D    ┆ some       ┆ ... ┆ 68       ┆ 78         ┆ 77         ┆ null       │
│      ┆        ┆            ┆ college    ┆     ┆          ┆            ┆            ┆            │
│ 1000 ┆ female ┆ group D    ┆ some       ┆ ... ┆ 77       ┆ 86         ┆ 86         ┆ null       │
│      ┆        ┆            ┆ college    ┆     ┆          ┆            ┆            ┆            │
└──────┴────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘